name: 'Run Playwright UI tests'

on:
  pull_request:

env:
  USER_EMAIL: ${{ secrets.USER_EMAIL }}
  USER_PASSWORD: ${{ secrets.USER_PASSWORD }}

jobs:
    run-tests:
        timeout-minutes: 60
        runs-on: ubuntu-20.04
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
            distribution: 'zulu'
            java-version: '11.0.12'
        - uses: actions/setup-node@v3
          with:
            node-version: 16
        - name: Build (mvn clean install)
          run: |
            chmod +x ./travis.sh
            ./travis-build.sh
        - name: Install Playwright Browsers
          run: npx playwright install --with-deps
        - name: Run tests
          run: |
            chmod +x ./playwright-tests.sh
            ./playwright-tests.sh
          shell: bash
        - name: "Upload artifact"
          uses: actions/upload-artifact@v3
          if: always()
          with:
            name: playwright-report
            path: playwright-report/
            retention-days: 30
